### ISSUE TITLE
tickCount property doesn't work

### ISSUE THREAD

**Issue by patientplatypus** [kristw/react-vega#10]
I'm trying to get a react-vega visualization to work with the tickCount property. I pass in data from an API call (successfully) but the tickCount property doesnt render the amount of ticks that I specify on the xAxis (although it does on the Y). I have made sure that the xAxis values I pass are numbers (from 0 to n) and are formatted the same way as the Y axis numbers. This is very frustrating - can you give advice on how to fix?

  ```
"axes": [
    {"orient": "bottom", "scale": "x",
      "title": "Date",
      "labelPadding": 10,
      "tickCount": 50
    },
    {"orient": "left", "scale": "y",
      "labelPadding": 10,
      "tickCount": 5
    }
  ],
```

**Comment by kristw** [comment]
Please check with the [vega documentation](https://vega.github.io/vega/docs/). The `tickCount` works similarly with how `d3` library works. It is only used as a guideline. So in some case, it may not return the exact number of ticks you put in the `tickCount` field. How many ticks did it render instead of 5?

**Comment by kristw** [comment]
Closed due to inactivity.
